---
apiVersion: v1
kind: Namespace
metadata:
  name: stg-01

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: python
  namespace: stg-01

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clone
  namespace: stg-01
spec:
  replicas: 3
  selector:
    matchLabels:
      app: clone
  template:
    metadata:
      labels:
        app: clone
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'madness'
        vault.hashicorp.com/agent-inject-secret-env.ini: 'secret/data/example/stg-01'
        vault.hashicorp.com/agent-inject-template-env.ini: |
          {{- with secret "secret/data/example/stg-01" -}}
          REDIS_PASSWORD={{ .Data.data.REDIS_PASSWORD }}
          {{- end }}
        vault.hashicorp.com/log-level: 'debug'
    spec:
      serviceAccountName: python
      containers:
        - name: clone
          image: busybox:latest
          command: ["/bin/sh", "-c", "sleep 3600"]
          workingDir: /vault/secrets
