---
apiVersion: v1
kind: Namespace
metadata:
  name: prd-01

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: python
  namespace: prd-01

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: prd-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'madness'
        vault.hashicorp.com/agent-inject-secret-env.ini: 'secret/data/example/dev-01'
        vault.hashicorp.com/agent-inject-template-env.ini: |
          {{- with secret "secret/data/example/dev-01" -}}
          MYSQL_USER={{ .Data.data.MYSQL_USER }}
          MYSQL_PASSWORD={{ .Data.data.MYSQL_PASSWORD }}
          {{- end }}
        vault.hashicorp.com/log-level: 'debug'
    spec:
      serviceAccountName: python
      containers:
        - name: busybox
          image: busybox:latest
          command: ["/bin/sh", "-c", "sleep 3600"]
          workingDir: /vault/secrets
